### ISSUE TITLE
Give me credits, this is not a fork you are just stealing my content

### ISSUE THREAD

**Issue by xtekky** [jassimtechcamp/tiktok-bot#1]

**Comment by jassimtechcamp** [comment]
I apologize, I did not steal from you, I kept your project as it is, even when pressing and starting, the project shows the name of the programmer
Because the project did not work for me, I initially modified it
 But in order to preserve the rights, I will delete it and I apologize to you

**Comment by xtekky** [comment]
You can modify, It by simply forking a project: https://docs.github.com/en/get-started/quickstart/fork-a-repo 
There is not problems with that.
